#!/usr/bin/env python3
"""Build plugin artifacts from src/.

Outputs:

  Repo root (Claude Code plugin — plugin `carono-wf` via marketplace `carono`):
    agents/*.md                         (from src/agents/)
    skills/<name>/...                   (from src/skills/)

The plugin manifest (.claude-plugin/plugin.json and .claude-plugin/marketplace.json)
is static — committed as-is, not generated by this script.

Usage:
    python build.py              # build all targets, write to repo root
    python build.py plugin       # only the plugin (repo root)
    python build.py --check      # CI-friendly: build into tempdir, validate,
                                   compare with current artifacts; exit 1 on
                                   any drift or validation error. Does NOT
                                   modify the working tree.

After every build (and inside --check) Tier-1 validation runs over the produced
artifacts: frontmatter has `name`/`description`, no unresolved `{{VAR}}`,
agent/skill names are unique within their group.

NOTE: opencode build is temporarily disabled — see commented-out build_opencode()
below. Re-enable when we're ready to validate compatibility again.
"""

import argparse
import filecmp
import os
import re
import shutil
import subprocess
import sys
import tempfile

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(SCRIPT_DIR))
SRC = os.path.join(ROOT, "src")
DIST = os.path.join(ROOT, "dist")
FORMAT_SCRIPT = os.path.join(SCRIPT_DIR, "format.py")

ALL_TARGETS = ["plugin"]


def load_template_variables() -> dict:
    """Read rules and templates files and return as template variables."""
    variables = {}

    sec_path = os.path.join(SRC, "rules", "security.md")
    if os.path.isfile(sec_path):
        with open(sec_path, encoding="utf-8") as f:
            variables["{{RULES_SECURITY}}"] = f.read()

    stop_path = os.path.join(SRC, "rules", "stop-and-ask.md")
    if os.path.isfile(stop_path):
        with open(stop_path, encoding="utf-8") as f:
            variables["{{RULES_STOP_AND_ASK}}"] = f.read()

    for tpl_name in ("WORKFLOW", "PROJECT", "TECH", "BOT", "MISSION", "ROADMAP", "MANUAL_INTERVENTIONS"):
        tpl_path = os.path.join(SRC, "templates", f"{tpl_name}.md")
        if os.path.isfile(tpl_path):
            with open(tpl_path, encoding="utf-8") as f:
                variables[f"{{{{TEMPLATE_{tpl_name}}}}}"] = f.read()

    return variables


def substitute_variables(content: str, variables: dict) -> str:
    for placeholder, value in variables.items():
        content = content.replace(placeholder, value)
    return content


def run_format(input_path: str, platform: str, output_path: str, variables: dict, out_root: str) -> bool:
    """Convert a Markdown file via format.py, with template variable substitution."""
    with open(input_path, encoding="utf-8") as f:
        content = f.read()
    content = substitute_variables(content, variables)

    tmp_path = input_path + ".tmp.resolved"
    with open(tmp_path, "w", encoding="utf-8") as f:
        f.write(content)

    cmd = [
        sys.executable, FORMAT_SCRIPT,
        tmp_path, platform,
        "--style", "markdown",
        "--output", output_path,
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    os.remove(tmp_path)

    if result.returncode != 0:
        print(f"  ERROR: {result.stderr.strip()}", file=sys.stderr)
        return False

    rel_in = os.path.relpath(input_path, ROOT)
    rel_out = os.path.relpath(output_path, out_root)
    print(f"  {rel_in} -> {rel_out}")
    return True


def copy_skills(dst_root: str, variables: dict) -> int:
    """Copy src/skills/<name>/ to <dst_root>/<name>/ with SKILL.md variable substitution."""
    skills_src = os.path.join(SRC, "skills")
    if not os.path.isdir(skills_src):
        return 0

    os.makedirs(dst_root, exist_ok=True)
    count = 0

    for skill_name in sorted(os.listdir(skills_src)):
        src_dir = os.path.join(skills_src, skill_name)
        if not os.path.isdir(src_dir):
            continue

        dst_dir = os.path.join(dst_root, skill_name)
        os.makedirs(dst_dir, exist_ok=True)

        for dirpath, dirnames, filenames in os.walk(src_dir):
            dirnames.sort()
            rel = os.path.relpath(dirpath, src_dir)
            out_sub = dst_dir if rel == "." else os.path.join(dst_dir, rel)
            os.makedirs(out_sub, exist_ok=True)

            for fname in sorted(filenames):
                src_file = os.path.join(dirpath, fname)
                dst_file = os.path.join(out_sub, fname)

                if fname == "SKILL.md":
                    with open(src_file, encoding="utf-8") as f:
                        content = f.read()
                    content = substitute_variables(content, variables)
                    with open(dst_file, "w", encoding="utf-8") as f:
                        f.write(content)
                else:
                    shutil.copy2(src_file, dst_file)

                rel_in = os.path.relpath(src_file, ROOT)
                rel_out = os.path.relpath(dst_file, dst_root)
                print(f"  {rel_in} -> skills/{rel_out}")
                count += 1

    return count


def build_plugin(out_root: str) -> int:
    """Build plugin layout into out_root: <out_root>/agents/ and <out_root>/skills/."""
    variables = load_template_variables()
    total = 0

    agents_dst = os.path.join(out_root, "agents")
    skills_dst = os.path.join(out_root, "skills")
    for path in (agents_dst, skills_dst):
        if os.path.isdir(path):
            shutil.rmtree(path)

    os.makedirs(agents_dst, exist_ok=True)
    src_dir = os.path.join(SRC, "agents")
    if os.path.isdir(src_dir):
        for fname in sorted(os.listdir(src_dir)):
            if not fname.endswith(".md"):
                continue
            out = os.path.join(agents_dst, fname)
            if run_format(os.path.join(src_dir, fname), "claude-code", out, variables, out_root):
                total += 1

    total += copy_skills(skills_dst, variables)
    return total


# ---------------------------------------------------------------------------
# OpenCode build is temporarily disabled. The function is kept for future use —
# when re-enabling, also restore "opencode" in ALL_TARGETS and the dispatch
# branch in main(). Note: src/tools/ no longer exists, so the original loop
# over ("agents", "tools") needs to be reduced to just "agents" — or revisited
# entirely depending on how OpenCode integration evolves.
# ---------------------------------------------------------------------------
# def build_opencode(out_root: str) -> int:
#     """Build <out_root>/dist/opencode/ — agents/, skills/."""
#     ...


# ---------------------------------------------------------------------------
# Tier-1 validation
# ---------------------------------------------------------------------------

PLACEHOLDER_RE = re.compile(r"\{\{[A-Z_][A-Z0-9_]*\}\}")
FRONTMATTER_KEY_RE = re.compile(r"^([A-Za-z][A-Za-z0-9_-]*)\s*:\s*(.*)$")


def parse_frontmatter(text: str):
    """Return (frontmatter_dict, body) or (None, text) if no frontmatter.

    Minimal YAML parser — only top-level `key: value` pairs needed for
    Tier-1 validation. Multi-line values, lists and nested objects are not
    supported (and not used in our SKILL.md / agent files)."""
    if not text.startswith("---\n"):
        return None, text
    end = text.find("\n---\n", 4)
    if end == -1:
        return None, text
    block = text[4:end]
    body = text[end + 5:]
    fm = {}
    for line in block.splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        m = FRONTMATTER_KEY_RE.match(line)
        if m:
            fm[m.group(1)] = m.group(2).strip()
    return fm, body


def collect_artifacts(plugin_root: str):
    """Yield (kind, path) for every file we want to validate."""
    agents_dir = os.path.join(plugin_root, "agents")
    if os.path.isdir(agents_dir):
        for fname in sorted(os.listdir(agents_dir)):
            if fname.endswith(".md"):
                yield "agent", os.path.join(agents_dir, fname)

    skills_dir = os.path.join(plugin_root, "skills")
    if os.path.isdir(skills_dir):
        for skill_name in sorted(os.listdir(skills_dir)):
            skill_md = os.path.join(skills_dir, skill_name, "SKILL.md")
            if os.path.isfile(skill_md):
                yield "skill", skill_md


def validate(plugin_root: str) -> list:
    """Run Tier-1 validation. Returns list of error strings (empty = OK)."""
    errors = []
    seen_names = {"agent": {}, "skill": {}}

    for kind, path in collect_artifacts(plugin_root):
        rel = os.path.relpath(path, plugin_root)
        try:
            with open(path, encoding="utf-8") as f:
                text = f.read()
        except OSError as e:
            errors.append(f"{rel}: cannot read ({e})")
            continue

        fm, body = parse_frontmatter(text)
        if fm is None:
            errors.append(f"{rel}: missing or malformed frontmatter")
            continue

        for required in ("name", "description"):
            if not fm.get(required):
                errors.append(f"{rel}: frontmatter missing `{required}`")

        unresolved = sorted(set(PLACEHOLDER_RE.findall(text)))
        if unresolved:
            errors.append(f"{rel}: unresolved placeholder(s) {', '.join(unresolved)}")

        name = fm.get("name")
        if name:
            prev = seen_names[kind].get(name)
            if prev:
                errors.append(f"{rel}: duplicate {kind} name `{name}` (also in {prev})")
            else:
                seen_names[kind][name] = rel

    return errors


# ---------------------------------------------------------------------------
# --check mode (CI: build into tempdir, validate, compare with working tree)
# ---------------------------------------------------------------------------


def collect_relpaths(root: str) -> set:
    """Return set of file paths under root, relative to root."""
    out = set()
    if not os.path.isdir(root):
        return out
    for dirpath, _, filenames in os.walk(root):
        for fname in filenames:
            full = os.path.join(dirpath, fname)
            out.add(os.path.relpath(full, root))
    return out


def diff_dirs(actual: str, expected: str) -> list:
    """Return list of human-readable diff messages between two directory trees."""
    diffs = []
    actual_files = collect_relpaths(actual)
    expected_files = collect_relpaths(expected)

    for missing in sorted(expected_files - actual_files):
        diffs.append(f"  missing in working tree: {missing}")
    for extra in sorted(actual_files - expected_files):
        diffs.append(f"  unexpected in working tree: {extra}")
    for common in sorted(actual_files & expected_files):
        a = os.path.join(actual, common)
        b = os.path.join(expected, common)
        if not filecmp.cmp(a, b, shallow=False):
            diffs.append(f"  content differs: {common}")
    return diffs


def run_check() -> int:
    """Build into a tempdir, validate, compare with working tree. Returns exit code."""
    print("Running build --check (no working tree modifications)\n")

    with tempfile.TemporaryDirectory(prefix="caronowf-build-") as tmp:
        print(f"[plugin] building into {tmp}")
        try:
            build_plugin(tmp)
        except Exception as e:
            print(f"\nBUILD ERROR: {e}", file=sys.stderr)
            return 2

        print("\n[validate]")
        errors = validate(tmp)
        if errors:
            for e in errors:
                print(f"  {e}", file=sys.stderr)
            print(f"\n{len(errors)} validation error(s).", file=sys.stderr)
            return 1
        print("  OK")

        print("\n[diff vs working tree]")
        all_diffs = []
        for sub in ("agents", "skills"):
            d = diff_dirs(os.path.join(ROOT, sub), os.path.join(tmp, sub))
            if d:
                all_diffs.append(f"\n  {sub}/")
                all_diffs.extend(d)

        if all_diffs:
            print("Working tree is out of sync with src/. Run `python3 src/scripts/build.py` and commit.", file=sys.stderr)
            for line in all_diffs:
                print(line, file=sys.stderr)
            return 1

        print("  in sync")

    print("\nAll checks passed.")
    return 0


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("target", nargs="?", choices=ALL_TARGETS, help="Build only this target (default: all)")
    parser.add_argument("--check", action="store_true", help="CI mode: build into tempdir, validate, compare to working tree, exit 1 on drift")
    args = parser.parse_args()

    if args.check:
        sys.exit(run_check())

    targets = [args.target] if args.target else ALL_TARGETS

    print("Building from src/")

    total = 0
    for t in targets:
        print(f"\n[{t}]")
        if t == "plugin":
            total += build_plugin(ROOT)
        # elif t == "opencode":
        #     total += build_opencode(ROOT)

    print(f"\nDone. {total} file(s) processed.")

    print("\n[validate]")
    errors = validate(ROOT)
    if errors:
        for e in errors:
            print(f"  {e}", file=sys.stderr)
        print(f"\n{len(errors)} validation error(s).", file=sys.stderr)
        sys.exit(1)
    print("  OK")


if __name__ == "__main__":
    main()
