#!/usr/bin/env python3
"""Build plugin artifacts from src/.

Outputs:

  Repo root (Claude Code plugin — plugin `carono-wf` via marketplace `carono`):
    agents/*.md                         (from src/agents/ + src/tools/)
    skills/<name>/...                   (from src/skills/)

  dist/opencode/ (for users wiring into OpenCode manually — no plugin concept there):
    agents/*.md                         (from src/agents/)
    tools/*.md                          (from src/tools/)
    skills/<name>/...                   (from src/skills/)

The plugin manifest (.claude-plugin/plugin.json and .claude-plugin/marketplace.json)
is static — committed as-is, not generated by this script.

Usage:
    python build.py              # build all targets
    python build.py plugin       # only the plugin (repo root)
    python build.py opencode     # only dist/opencode/
"""

import argparse
import os
import shutil
import subprocess
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(SCRIPT_DIR))
SRC = os.path.join(ROOT, "src")
DIST = os.path.join(ROOT, "dist")
FORMAT_SCRIPT = os.path.join(SCRIPT_DIR, "format.py")

ALL_TARGETS = ["plugin", "opencode"]


def load_template_variables() -> dict:
    """Read rules and templates files and return as template variables."""
    variables = {}

    sec_path = os.path.join(SRC, "rules", "security.md")
    if os.path.isfile(sec_path):
        with open(sec_path, encoding="utf-8") as f:
            variables["{{RULES_SECURITY}}"] = f.read()

    for tpl_name in ("WORKFLOW", "PROJECT", "TECH", "BOT"):
        tpl_path = os.path.join(SRC, "templates", f"{tpl_name}.md")
        if os.path.isfile(tpl_path):
            with open(tpl_path, encoding="utf-8") as f:
                variables[f"{{{{TEMPLATE_{tpl_name}}}}}"] = f.read()

    return variables


def substitute_variables(content: str, variables: dict) -> str:
    for placeholder, value in variables.items():
        content = content.replace(placeholder, value)
    return content


def run_format(input_path: str, platform: str, output_path: str, variables: dict) -> bool:
    """Convert a Markdown file via format.py, with template variable substitution."""
    with open(input_path, encoding="utf-8") as f:
        content = f.read()
    content = substitute_variables(content, variables)

    tmp_path = input_path + ".tmp.resolved"
    with open(tmp_path, "w", encoding="utf-8") as f:
        f.write(content)

    cmd = [
        sys.executable, FORMAT_SCRIPT,
        tmp_path, platform,
        "--style", "markdown",
        "--output", output_path,
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    os.remove(tmp_path)

    if result.returncode != 0:
        print(f"  ERROR: {result.stderr.strip()}", file=sys.stderr)
        return False

    rel_in = os.path.relpath(input_path, ROOT)
    rel_out = os.path.relpath(output_path, ROOT)
    print(f"  {rel_in} -> {rel_out}")
    return True


def copy_skills(dst_root: str, variables: dict) -> int:
    """Copy src/skills/<name>/ to <dst_root>/<name>/ with SKILL.md variable substitution."""
    skills_src = os.path.join(SRC, "skills")
    if not os.path.isdir(skills_src):
        return 0

    os.makedirs(dst_root, exist_ok=True)
    count = 0

    for skill_name in sorted(os.listdir(skills_src)):
        src_dir = os.path.join(skills_src, skill_name)
        if not os.path.isdir(src_dir):
            continue

        dst_dir = os.path.join(dst_root, skill_name)
        os.makedirs(dst_dir, exist_ok=True)

        for dirpath, dirnames, filenames in os.walk(src_dir):
            dirnames.sort()
            rel = os.path.relpath(dirpath, src_dir)
            out_sub = dst_dir if rel == "." else os.path.join(dst_dir, rel)
            os.makedirs(out_sub, exist_ok=True)

            for fname in sorted(filenames):
                src_file = os.path.join(dirpath, fname)
                dst_file = os.path.join(out_sub, fname)

                if fname == "SKILL.md":
                    with open(src_file, encoding="utf-8") as f:
                        content = f.read()
                    content = substitute_variables(content, variables)
                    with open(dst_file, "w", encoding="utf-8") as f:
                        f.write(content)
                else:
                    shutil.copy2(src_file, dst_file)

                rel_in = os.path.relpath(src_file, ROOT)
                rel_out = os.path.relpath(dst_file, ROOT)
                print(f"  {rel_in} -> {rel_out}")
                count += 1

    return count


def build_plugin() -> int:
    """Build plugin layout at repo root: agents/ and skills/.

    `src/agents/` and `src/tools/` are merged into a single `agents/` folder —
    Claude Code plugins expose only one subagent directory; the src/ split is
    logical (business agents vs service agents), not structural.
    """
    variables = load_template_variables()
    total = 0

    agents_dst = os.path.join(ROOT, "agents")
    skills_dst = os.path.join(ROOT, "skills")
    for path in (agents_dst, skills_dst):
        if os.path.isdir(path):
            shutil.rmtree(path)

    os.makedirs(agents_dst, exist_ok=True)
    for subdir in ("agents", "tools"):
        src_dir = os.path.join(SRC, subdir)
        if not os.path.isdir(src_dir):
            continue
        for fname in sorted(os.listdir(src_dir)):
            if not fname.endswith(".md"):
                continue
            out = os.path.join(agents_dst, fname)
            if os.path.exists(out):
                print(f"  ERROR: name collision at {out} — src/agents/ and src/tools/ both contain {fname}", file=sys.stderr)
                sys.exit(1)
            if run_format(os.path.join(src_dir, fname), "claude-code", out, variables):
                total += 1

    total += copy_skills(skills_dst, variables)
    return total


def build_opencode() -> int:
    """Build dist/opencode/ — agents/, tools/, skills/ (OpenCode has no plugin concept)."""
    variables = load_template_variables()
    base = os.path.join(DIST, "opencode")
    if os.path.isdir(base):
        shutil.rmtree(base)

    total = 0
    for subdir in ("agents", "tools"):
        src_dir = os.path.join(SRC, subdir)
        if not os.path.isdir(src_dir):
            continue
        dst_dir = os.path.join(base, subdir)
        os.makedirs(dst_dir, exist_ok=True)
        for fname in sorted(os.listdir(src_dir)):
            if not fname.endswith(".md"):
                continue
            if run_format(os.path.join(src_dir, fname), "opencode", os.path.join(dst_dir, fname), variables):
                total += 1

    total += copy_skills(os.path.join(base, "skills"), variables)
    return total


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("target", nargs="?", choices=ALL_TARGETS, help="Build only this target (default: all)")
    args = parser.parse_args()

    targets = [args.target] if args.target else ALL_TARGETS

    print("Building from src/")

    total = 0
    for t in targets:
        print(f"\n[{t}]")
        if t == "plugin":
            total += build_plugin()
        elif t == "opencode":
            total += build_opencode()

    print(f"\nDone. {total} file(s) processed.")


if __name__ == "__main__":
    main()
